; Hardware definitions

.DEFINE LCDC $FF40				; LCD Control
.DEFINE STAT $FF41				; LCDC Status
.DEFINE VBK	$FF4F				; VRAM Bank
.DEFINE SVBK $FF70				; WRAM Bank
.DEFINE BCPS $FF68				; Background Palette Index (GBC)
.DEFINE BCPD $FF69				; Background Palette Data (GBC)
.DEFINE OCPS $FF6A				; Sprite Palette Index (GBC)
.DEFINE OCPD $FF6B				; Sprite Palette Data (GBC)

.DEFINE ROM0 $0000
.DEFINE ROM1 $4000
.DEFINE WRAM0 $C000
.DEFINE WRAM1 $D000


; Constants
.DEFINE CHANGE_BANK				$2100

; Definitions
.DEFINE WRAM_DEFAULT_BANK		0x01
.DEFINE WRAM_METATILE_BANK		0x02
.DEFINE WRAM_PALETTE_BANK 		0x03
.DEFINE WRAM_BATTLE_BANK		0x04

.DEFINE WRAM_PALETTE_ADDR 		WRAM1
.DEFINE WRAM_PALETTE_SIZE		0x40
.DEFINE WRAM_PALETTE_FADECOUNT	0x4
.DEFINE WRAM_BGPALETTE_ADDR 	WRAM1
.DEFINE WRAM_OBJPALETTE_ADDR 	WRAM1 + WRAM_PALETTE_SIZE
.DEFINE WRAM_BATTLEPALETTE_ADDR	WRAM1 + WRAM_PALETTE_SIZE * 2
.DEFINE WRAM_FADE_CODE			$D400

.DEFINE WRAM_BATTLE_CODE			 		$DE00
.DEFINE WRAM_BATTLE_ENEMYTILEATTR_ADDR 		$DF00
.DEFINE WRAM_BATTLE_ENEMYIDS_ADDR			$DFF0