.DEFINE COLOR_GRAY 		$00
.DEFINE COLOR_RED 		$01
.DEFINE COLOR_ORANGE	$02
.DEFINE COLOR_GREEN		$03
.DEFINE COLOR_AQUA		$04
.DEFINE COLOR_BLUE		$05
.DEFINE COLOR_PURPLE	$06

.BANK $10 SLOT 1
.SECTION "Enemy_Tile_Attributes" FREE
EnemyTileAttributes_Start:
;	00 FUNGUS		01 MUSHROOM
.db COLOR_GREEN, 	COLOR_ORANGE
;	02 STARFISH		03 PENTAGON
.db COLOR_ORANGE, 	COLOR_PURPLE	
;	04 F-DRAKE		05 F-LIZ		06 SALAMAND
.db COLOR_ORANGE,	COLOR_RED,		COLOR_GREEN
;	07 RAVEN		08 AMPREX		09 GRIFFON
.db COLOR_PURPLE,	COLOR_BLUE,		COLOR_GREEN
;	0A WORM			0B LANDWORM		0C GIGAWORM
.db COLOR_ORANGE,	COLOR_GREEN,	COLOR_BLUE
;	0D TURTLE		0E ADAMANT		0F IGASAUR
.db COLOR_GREEN,	COLOR_BLUE,		COLOR_RED
;	10 WHISPER		11 FIREBALL
.db COLOR_AQUA,		COLOR_RED
;	12 BIG EYE		13 EVIL EYE
.db COLOR_AQUA,		COLOR_PURPLE
;	14 BLACK CAT	15 MUMMYCAT
.db COLOR_PURPLE,	COLOR_GRAY
;	16 SQUID		17 AMOEBA
.db COLOR_AQUA,		COLOR_ORANGE
;	18 TIRE 		19 WHEEL		1A FIREFAN
.db COLOR_AQUA,		COLOR_BLUE,		COLOR_RED
;	1B BABYWYRM		1C WYRM KID		1D WYRM
.db COLOR_ORANGE,	COLOR_AQUA,		COLOR_GREEN
;	1E WOLF			1F GREYWOLF		20 ROMULUS
.db COLOR_AQUA,		COLOR_GRAY,		COLOR_ORANGE
;	21 RAY			22 DRAINRAY		23 BOLTRAY
.db COLOR_PURPLE,	COLOR_BLUE,		COLOR_PURPLE
;	24 D.BONE		25 D.FOSSIL
.db COLOR_GRAY,		COLOR_RED
;	26 TYPHOON		27 TEMPEST
.db COLOR_GRAY,		COLOR_PURPLE
;	28 SCORPION		29 HUNTER
.db COLOR_ORANGE,	COLOR_AQUA
;	2A ANGLER		2B BULBFISH
.db COLOR_GREEN,	COLOR_BLUE
;	2C DUALMASK		2D EVILMASK
.db COLOR_ORANGE,	COLOR_RED
;	2E GHOST		2F SPECTER
.db COLOR_GRAY,		COLOR_PURPLE
;	30 SNAKE		31 SERPENT		32 HYDRA
.db COLOR_GREEN,	COLOR_RED,		COLOR_PURPLE
;	33 OCTOPUS		34 AMMONITE		35 KRAKEN
.db COLOR_BLUE,		COLOR_AQUA,		COLOR_PURPLE
;	36 BABY-D		37 YOUNG-D		38 SEI-RYU
.db COLOR_ORANGE,	COLOR_GREEN,	COLOR_RED
;	39 GARGOYLE		3A REMORA		3B GARUDA
.db COLOR_GRAY,		COLOR_GREEN,	COLOR_ORANGE
;	3C SILVER		3D KELPIE		3E MUSTANG		3F CENTAUR		40 NITEMARE
.db COLOR_GRAY,		COLOR_GREEN,	COLOR_ORANGE,	COLOR_AQUA,		COLOR_PURPLE
;	41 ORC-ORC		42 MAD BOAR 	43 PIRATE		44 WEREPIG		45 VIKING
.db COLOR_ORANGE,	COLOR_GREEN,	COLOR_BLUE,		COLOR_GRAY,		COLOR_PURPLE
;	46 DIVINER		47 BROOMER		48 WITCH		49 MAGICIAN		4A WIZARD
.db COLOR_AQUA,		COLOR_ORANGE,	COLOR_BLUE,		COLOR_GRAY,		COLOR_PURPLE
;	4B SPRITE		4C NYMPH		4D FAIRY		4E PIXIE		4F SYLPH
.db COLOR_ORANGE,	COLOR_AQUA,		COLOR_BLUE,		COLOR_GREEN,	COLOR_PURPLE
;	50 MEDUSA		51 LAMIA		52 NAGA			53 SCYLLA		54 ECHIDNA
.db COLOR_GRAY,		COLOR_GREEN,	COLOR_ORANGE,	COLOR_BLUE,		COLOR_RED
;	55 FISH MAN 	56 MERMAN		57 NIX			58 SELKIE		59 GILL MAN
.db COLOR_AQUA,		COLOR_BLUE,		COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED
;	5A WATCHER		5B HERMIT		5C MAGE			5D SORCERER		5E WARLOCK
.db COLOR_AQUA,		COLOR_ORANGE,	COLOR_BLUE,		COLOR_GRAY,		COLOR_PURPLE
;	5F THANOS		60 SOARX		61 SIREN		62 SUCCUBUS		63 SPHINX
.db COLOR_PURPLE,	COLOR_AQUA,		COLOR_BLUE,		COLOR_RED,		COLOR_ORANGE
;	64 FIGHTER		65 WARRIOR		66 LIZ MAN 		67 LIZ DUKE		68 LIZ KING
.db COLOR_ORANGE,	COLOR_AQUA,		COLOR_GREEN,	COLOR_BLUE,		COLOR_PURPLE
;	69 SEAMONK		6A SALTMONK		6B BROODER		6C BIG HEAD 	6D DAGON
.db COLOR_AQUA,		COLOR_GRAY,		COLOR_GREEN,	COLOR_ORANGE,	COLOR_RED
;	6E THOTH		6F HORUS		72 OSIRIS		73 SET 			76 ANUBIS
.db COLOR_ORANGE,	COLOR_AQUA,		COLOR_GREEN,	COLOR_BLUE,		COLOR_PURPLE
;	70 FAMILIAR		71 FIEND		74 LOKI			75 MEPHISTO		77 AESHMA
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	78 HOOLIGAN		79 THIEF		7A BURGLER		7B BRIGAND		7C OUTLAW
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	7D QUACKY		7E STRANGER		7F IMPOSTER		80 LOONYGUY		81 CRACKER
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	82 SOLDIER		83 TERORIST		84 COMMANDO		85 HIREDGUN		86 SS
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	87 RONIN		88 SAMURAI		89 HATAMOTO		8A DAIMYO		8B SHOGUN
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	8C TALKER		8D BUSYBODY		8E RUMORER		8F TATTLER		90 VIRAGO
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	91 HEADLESS		92 DUKE			93 DULLAHAN		94 BRAIN 		95 REMOVED
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	96 ORB RAT 		97 TOMTOM		98 JERRIT		99 MAITIE		9A SPECTRAT
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	9B FLOWER		9C COSMOS		9D IRONROSE		9E REAPER		9F CACTUS
.db COLOR_GREEN,	COLOR_PURPLE,	COLOR_RED,		COLOR_GRAY,		COLOR_ORANGE
;	A0 GUARD		A1 KEEPER		A2 MONITOR		A3 SEARCHER		A4 ALERT
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	A5 BAZOOKA		A6 75MM			A7 105MM		A8 150MM		A9 210MM
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	AA TRIXSTER		AB CON MAN 		AC BEGUILER		AD SWINDLER		AE HUSTLER
.db COLOR_ORANGE,	COLOR_PURPLE,	COLOR_GREEN,	COLOR_RED,		COLOR_GRAY
;	AF AIRMAID		B0 IRONLADY		B1 VALKYRIE		B2 IKEN			B3 VENUS
.db COLOR_AQUA,		COLOR_GRAY,		COLOR_GREEN,	COLOR_RED,		COLOR_ORANGE
;	B4 WATERHAG
.db COLOR_AQUA
;	B5 DWELG
.db COLOR_ORANGE
;	B6 LARA
.db COLOR_RED
;	B7 JORGANDR
.db COLOR_ORANGE
;	B8 ASHURA
.db COLOR_AQUA
;	B9 DOGRA
.db COLOR_ORANGE
;	BA CHAOS
.db COLOR_ORANGE
;	BB MAITREYA
.db COLOR_ORANGE
;	BC FENRIR
.db COLOR_GREEN
;	BD GUHA
.db COLOR_PURPLE
;	BE DAHAK
.db COLOR_ORANGE
;	BF AGRON
.db COLOR_BLUE
;	C0 BALLOR
.db COLOR_RED
;	C1 SOL
.db COLOR_ORANGE
;	C2 XAGOR
.db COLOR_ORANGE
EnemyTileAttributes_End:
.ENDS
